# Generated by Django 4.2.13 on 2026-06-03 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('low_quality', 'Faible qualité / Low quality'), ('factual_error', 'Erreur factuelle / Factual error'), ('inappropriate', 'Contenu inapproprié / Inappropriate')], max_length=30, verbose_name='motif')),
                ('details', models.TextField(blank=True, verbose_name='détails')),
                ('is_valid', models.BooleanField(blank=True, null=True, verbose_name='signal valide')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='courses.course', verbose_name='cours')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL, verbose_name='signaleur')),
            ],
            options={
                'verbose_name': 'signalement',
                'verbose_name_plural': 'signalements',
                'ordering': ['-created_at'],
                'unique_together': {('reporter', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ModerationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approuver / Approve'), ('reject', 'Rejeter / Reject')], max_length=20, verbose_name='décision')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_reviews', to='courses.course', verbose_name='cours')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='modérateur')),
            ],
            options={
                'verbose_name': 'avis de modération',
                'verbose_name_plural': 'avis de modération',
                'ordering': ['-created_at'],
                'unique_together': {('moderator', 'course')},
            },
        ),
    ]
