# Generated by Django 4.2.13 on 2026-06-03 08:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100, verbose_name='nom (fr)')),
                ('name_en', models.CharField(max_length=100, verbose_name='name (en)')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='📚', max_length=50)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['name_fr'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('level', models.CharField(choices=[('beginner', 'Débutant / Beginner'), ('intermediate', 'Intermédiaire / Intermediate'), ('expert', 'Expert')], default='beginner', max_length=20, verbose_name='niveau')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('both', 'Bilingue / Bilingual')], default='fr', max_length=10, verbose_name='langue')),
                ('status', models.CharField(choices=[('pending', 'En attente / Pending'), ('approved', 'Approuvé / Approved'), ('rejected', 'Rejeté / Rejected'), ('quarantine', 'Quarantaine / Quarantine')], default='pending', max_length=20, verbose_name='statut')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='motif de rejet')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='miniature')),
                ('is_low_bandwidth', models.BooleanField(default=False, help_text='Coché automatiquement si tous les modules < 50 Mo', verbose_name='faible bande passante')),
                ('total_size_mb', models.FloatField(default=0, verbose_name='taille totale (Mo)')),
                ('report_count', models.IntegerField(default=0, verbose_name='signalements')),
                ('enrollment_count', models.IntegerField(default=0, verbose_name='inscriptions')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='note moyenne')),
                ('rating_count', models.IntegerField(default=0, verbose_name='nombre de notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to=settings.AUTH_USER_MODEL, verbose_name='formateur')),
            ],
            options={
                'verbose_name': 'cours',
                'verbose_name_plural': 'cours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='vidéo')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='PDF')),
                ('video_compressed', models.FileField(blank=True, null=True, upload_to='videos/compressed/', verbose_name='vidéo compressée')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='durée (min)')),
                ('file_size_mb', models.FloatField(default=0, verbose_name='taille (Mo)')),
                ('is_downloadable', models.BooleanField(default=True, verbose_name='téléchargeable hors ligne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='cours')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='pourcentage')),
                ('last_position_seconds', models.IntegerField(default=0, verbose_name='dernière position (s)')),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'progression',
                'verbose_name_plural': 'progressions',
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inscription',
                'verbose_name_plural': 'inscriptions',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='étoiles')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'évaluation',
                'verbose_name_plural': 'évaluations',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
