# Generated by Django 4.2.13 on 2026-06-03 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_fr', models.CharField(max_length=100, verbose_name='nom (fr)')),
                ('name_en', models.CharField(max_length=100, verbose_name='name (en)')),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField(blank=True)),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('required_score', models.IntegerField(default=0)),
                ('is_special', models.BooleanField(default=False, help_text='Badge spécial Cameroun (local)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'badge',
                'ordering': ['required_score'],
            },
        ),
        migrations.CreateModel(
            name='ReputationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('course_approved', 'Cours approuvé (+10)'), ('like_received', 'Like reçu (+1)'), ('valid_report', 'Signalement validé (+2)'), ('badge_earned', 'Badge obtenu')], max_length=30, verbose_name="type d'événement")),
                ('points', models.IntegerField(default=0, verbose_name='points')),
                ('description_fr', models.CharField(blank=True, max_length=200)),
                ('description_en', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'événement de réputation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='reputation.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'badge utilisateur',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
